### ISSUE TITLE
How to create Impulse header files?

### ISSUE THREAD

**Issue by mikobuntu** [swh/ladspa#10]
Hi @swh , I tried contacting you through your public email, but i got a not sent error, anyway I have the general understanding on the structure of the .h files ( the impulses ) i can build a renamed copy of one of your originals and get it to work within the plugin no problem, my problem is i cannot for the life of me create the actual "array"? data e.g -0.0000747256300, +0.0004581413362, -0.0004988051100, +0.0080212860617, from my mono audio files. I have tried sox, audacity and wav2c so far. 
It would be greatly appreciated if you can point me in the right direction ... 

thanks Mikobuntu ;)

**Comment by tresf** [comment]
@swh this is a support request that has been answered.   I think it can be closed. :)
