### ISSUE TITLE
[PATCH] Add missing AM_GNU_GETTEXT_VERSION to configure.in

### ISSUE THREAD

**Issue by hartwork** [swh/ladspa#20]
```
# autoreconf -i
[..]
autoreconf-2.69: configure.in: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION
[..]
```
The patch is up at https://github.com/gentoo/gentoo/blob/15e6c749fedcecf606c368ee689ab051ab71c0db/media-plugins/swh-plugins/files/swh-plugins-0.4.15-gettext.patch

**Comment by swh** [comment]
Done.
