### ISSUE TITLE
How to run basic tests via command line?

### ISSUE THREAD

**Issue by binarykitchen** [swh/ladspa#39]
Do you have any examples hand how to run tests via command line? Just the very simple ones.

So that I can verify if compilation was successful.

Thanks :)

**Comment by swh** [comment]
You just need a command line LADSPA host, I think the LADSPA SDK used to ship with one.

I can't remember the syntax I'm afraid.

**Comment by binarykitchen** [comment]
how then can you develop software when unable to run tests??

**Comment by maxim-belkin** [comment]
@swh: what files (libraries) should 100% be present upon installation of the SWH Plugins?

**Comment by swh** [comment]
I no long actively develop this software, when I did the tests we're extremely complex (and required listening), so were never checked into the public repo, I have no idea what happened to them. They're probably lost.

**Comment by swh** [comment]
@maxim-belkin sorry, no idea, but the auto* stuff should tell you that, no?

**Comment by plater** [comment]
ladspa_sdk builds 3 binaries, analyseplugin, listplugins and applyplugin. I've never used applyplugin but analyseplugin is a good way of picking up errors.

**Comment by tresf** [comment]
This utility (`ecasound`) claims to support what is being requested, something such as a command line method for LADSPA effect testing.  It appears from the documentation that this too requires the LADSPA SDK to be installed and available.

https://ecasound.seul.org/ecasound/Documentation/examples.html#effects

**Comment by plater** [comment]
Any package that builds against ladspa requires the libs and headers ladspa is built from the sdk tarball simply install the devel package. ecasound is available in most distributions. In openSUSE you get it from Packman, don't know why, maybe a license issue.

**Comment by tresf** [comment]
@plater thanks for the information.

In regards to the OP's request, I would like to fulfill this request for unit testing capabilities.  My first step is to generate a LADSPA effect-modified sound.  Here is my progress so far, Ubuntu 14.04.

1. Install ecasound with ladspa support and other dependencies
   ```bash
   sudo apt-get install ecasound ladspa-sdk
   ```

2. Using a known `.wav` file, pass it through `ecasound` using the specified `LADSPA` name or `ID`
   ```bash
   # by name (-el:<name>)
   ecasound -i:/usr/share/sounds/alsa/Noise.wav -o:$HOME/Desktop/Noise-imp.wav -el:imp,1 
   
   # by id (-eli:<id>)
   ecasound -i:/usr/share/sounds/alsa/Noise.wav -o:$HOME/Desktop/Noise-1199.wav -eli:1199,1 
   ```

   This will produce the following error... 

   ```
   (eca-object-factory) ERROR: Unable to find LADSPA plugin "imp"
   [...]
   ecasound: ERROR: [ECA-SESSION] : "Invalid argument, unable to parse: "-el:imp,1""
   ```

3. Installing the package `swh-plugins` and the above command succeeds.  If you've recently uninstalled `swh-plugins`, reinstall using the apt `--reinstall` flag, seems to fix a packaging issue.

@plater So first question... how do we tell `ecasound` to look in a location other than default for the plugins?  Can we override the library search path, or is it hard-coded to look at the system location?

We can run `make install` as root, but it seems like an unnecessary step for a user-space unit-test.  Thanks in advance!

**Comment by plater** [comment]
Running ladspa's listplugins I see "Warning: You do not have a LADSPA_PATH environment variable set". Try setting this to the plugins installation path. In openSUSE x86_64 this is /usr/lib64/ladspa. This can't be set on installation because it is a per user path. Looking at rosegarden and likely other apps that use ladspa I see that it does a path search if LADSPA_PATH isn't set.

**Comment by tresf** [comment]
@plater perfect, that did the trick.  

```bash
# make install --prefix=$HOME/ladspa
export LADSPA_PATH=$HOME/ladspa/lib/ladspa
```

```bash
ecasound -i:/usr/share/sounds/alsa/Noise.wav -o:$HOME/Desktop/Noise-imp.wav -el:imp,1

sha256 /usr/share/sounds/alsa/Noise.wav
sha256 $HOME/Desktop/Noise-imp.wav
```

| File Name | Hash |
|-----------|------|
| `Noise.wav` | `0d897df` |
| `Noise-imp.wav` |  `9a08431` |

In this case, the hash differences are proof that the file contents are different.
The hash of the modified sound should always remain the same so long as the same input parameters are given to the plugin.

This should qualify as a basic LADSPA unit test.

**Comment by swh** [comment]
When I started working on these plugins 20(!) years ago I had a test suite of sorts, but I don't think I ever checked it in anywhere. I probably still have the source in a backup somewhere, but it was focussed more on checking for leaks and correctness to the spec that audio processing. E.g. making sure they didn't emit denormals under stress, and that they behaved themselves with different buffer sizes.

N.B. several plugins are non-deterministic, so hashing the output won't work in all cases.

If I ever have a day free I might write a test system, though I've not written any C for 5 or 6 years, so I'm a bit rusty.

**Comment by swh** [comment]
If instead of binary hashing the PCM signal there was a LSH of the FFT spectrum, that might work better for plugins that inject noise into the signal.

**Comment by tresf** [comment]
> E.g. making sure they didn't emit denormals under stress, and that they behaved themselves with different buffer sizes.

The downstream checks are not proper unit tests, (and we have no fuzzing) but downstream we're working to capture these denormals as well. https://github.com/LMMS/lmms/pull/3687

Which has helped us discover [these](https://github.com/LMMS/lmms/pull/3927/files#diff-0aafc6922df0312e0c069e7da246d8c7L839) (PR coming soon).

> N.B. several plugins are non-deterministic, so hashing the output won't work in all cases.

> > If instead of binary hashing the PCM signal there was a LSH of the FFT spectrum, that might work better for plugins that inject noise into the signal.

👍

**Comment by swh** [comment]
Nice one :+1:

**Comment by tresf** [comment]
A recommended tool from @softrabbit: https://github.com/cth103/plugin-torture

**Comment by swh** [comment]
Perfect!
