### ISSUE TITLE
configure.ac incorrect version

### ISSUE THREAD

**Issue by andreasstieger** [swh/ladspa#41]
latest release is 0.4.17, but configure.ac sais 0.4.15.
Also uploading bootstrapped tarballs to the release tag would be helpful.

**Comment by swh** [comment]
Updated version number in configure.ac

I don't currently have a machine that can build the tarballs, so can't push one.

**Comment by andreasstieger** [comment]
165b3dc97bb6645947d935c84c38d381c79f5300 thanks
