### ISSUE TITLE
Would Steve Harris consider updating/removing email address/contact ? 

### ISSUE THREAD

**Issue by BrootLee** [swh/ladspa#42]
Hi. When I need support about swh plugins, I mostly use the documentation PDF. From there I sometimes do external research/reading. Other times I ask other users, but really, there are occassions when contacting the author directly seems like the fastest way to get an answer. This is only occasional though.

The email address in the website doesn't work. Apparently Steve Harris is here, so maybe it would be good for him to link to github instead of steve@plugin.org.uk, or in the case he doesn't want users to contact him he could just remove the email address and suggest other things.
 That would be respectable

I wanted to ask about a SC compressors trick, but apparently the "issues" here deal with more technical, development related stuff. So instead I would like to know what is a good e.g. forum when there is knowledgeable people about Steve Harris' ladspa plugins, or even Steve himself under a different name and where I can ask about the plugins and situations?

Thank you and sorry if this doesn't belong here.

**Comment by swh** [comment]
Good point.

I'll update the website to point here.

The MX record for @plugin.org.uk no longer works, and I haven't been motivated enough to fix it.

**Comment by swh** [comment]
The website now points here, and I think there's no references to my email address in the HTML.
