### ISSUE TITLE
Loudness contour correction plug in

### ISSUE THREAD

**Issue by Neo595** [swh/ladspa#45]
Hi Steve,

I'm thinking to talk to you as you're very experimented on audio plugin and also after extensive search, I can't find any reference to "loudness" correction (physiological)  (as standard radio, amplifier).

So my question : Is somebody implement a loudness correction as a plugin that I can use in pulseaudio ?

https://en.wikipedia.org/wiki/Equal-loudness_contour

So, I don't know how to implement it and it seems rather hard. The aim is to design frequency dependent correction and also depending on SPL pressure to compensate loss of sensitivity of human ear at low SPL.

**Comment by swh** [comment]
I don't know of one exactly like that, but A-weighting is close, and there's a plugin for that:
http://users.skynet.be/solaris/linuxaudio/
