### ISSUE TITLE
How would one go about to convert this "plugin" to ladspa

### ISSUE THREAD

**Issue by fullmooninu** [swh/ladspa#48]
https://github.com/Decatf/gstreamer1.0-delta

I really want to try it, but I only know how to sequence ladspa filters in pulseaudio.

**Comment by swh** [comment]
You can achieve the same result with fewer artefacts by using a EQ band filter.

**Comment by fullmooninu** [comment]
can you explain? or direct me to an explanation?

**Comment by swh** [comment]
All that plugin is doing is boosting the high frequencies (but in an uncontrolled, and sample rate dependant way).

You could just add a high shelf EQ (or similar), set to boost, then you could control the cutoff and amount.

See http://www.presonus.com/community/learn/equalizer-terms-and-tips

**Comment by fullmooninu** [comment]
Thank you for your reply. :)

So from what I understand,  this plugin - delta - is just an equalizer with more or less fixed preset set to boost the volume of higher frequencies?  Am I right in thinking so?

So why are people so amazed at it? As you can see here: http://foosion.foobar2000.org/components/?id=delta

This is the original plugin page: http://foosion.foobar2000.org/components/?id=delta

And this is the page of the guy that says he exported that plugin above to Linux, supposedly the same one I showed you in a previous link https://decatf.wordpress.com/2010/11/04/gstreamer-delta-audio-sharpening-plugin/

With all this added info you confirm this is just an equaliser with a fixed preset?

**Comment by swh** [comment]
Yes, that's right.

I don't know why people are impressed with it.

**Comment by fullmooninu** [comment]
I'm gona try reading that delta code, and then figure out an equalizer curve that simulates it then. Tyvm for your replies. You mind if I ask you more stuff in the future?

**Comment by swh** [comment]
Sure, though I'm pretty rusty on DSP stuff, I've not worked in that area for some time.
