### ISSUE TITLE
mbeq frying sound !

### ISSUE THREAD

**Issue by balbuze** [swh/ladspa#58]
Hi!
Thank you for your great work!
I'm balbuze. I wrote a plugin for volumio https://volumio.org/ an audio os using mbeq.
I met the following problem : sometimes or on certain system, instead of the sound, I get a "frying" sound or something like a pink noise. If I stop playing and restart, everything is ok...
Do you know special value to be set in asound.conf (buffer, period) to avoid it. The problem occurs with mpd, or spotify connect on arm system (rpi , pine64) or even speaker-test.
other question : is there a interest of using sepexrate as resampler with mbeq ?
Thank you.

the asound file :

ctl.equal {
 type equal
library "/usr/lib/ladspa/mbeq_1197.so"
    module "mbeq"
}
pcm.plugequal1 {
 type equal
 library "/usr/lib/ladspa/mbeq_1197.so"
    module "mbeq"

 slave.pcm "plughw:0,0";
}
pcm.equal {
 type plug;
 slave.pcm plugequal1;
 }

**Comment by swh** [comment]
I've a feeling that might happen with certain parameter values - pretty sure it's no to do with the buffer size.

LADSPA doesn't support resampling - input rate and output rate have to be the same.

**Comment by balbuze** [comment]
Thanks for your quick answers. What parameter are you talking about? In asound.conf?

**Comment by swh** [comment]
The parameters to the plugin - I don't know how they're passed in your environment.
