### ISSUE TITLE
Gentoo building warnings  

### ISSUE THREAD

**Issue by CaptainBloodz** [swh/ladspa#65]
Builds fine on gentoo, typo & a few warnings reported at:
[https://bugs.gentoo.org/595812](url)

Thks 4 ur attention

**Comment by tresf** [comment]
Correct link (the above seems to have been poorly autocorrected by GitHub): https://bugs.gentoo.org/595812

**Comment by swh** [comment]
I'm not sure what the request is, the link provided isn't clear on which/what change you'd link applied.

**Comment by CaptainBloodz** [comment]
Let's close this as it seems solved with current release.
Plus laconic OP doesn't provide clear view indeed, which local evidences are long gone here.
