### ISSUE TITLE
Improved 'depth' of sound with modified SC4_1882 compressor

### ISSUE THREAD

**Issue by sammerw** [swh/ladspa#69]
Hello Steve

I modified part of code of SC4_1882.xml for Left/Right channel the following way
sc4_1882.xml

        sum += lev_in * lev_in;
 sum_l += la * la;
 sum_r += ra * ra;
        if (amp > env_rms) {
          env_rms = env_rms * ga + amp * (1.0f - ga);
        } else {
          env_rms = env_rms * gr + amp * (1.0f - gr);
        }
round_to_zero(&env_rms);
        if (lev_in > env_peak) {
          env_peak = env_peak * ga + lev_in * (1.0f - ga);
        } else {
//          env_peak = env_peak * gr + lev_in * (1.0f - gr);
         env_peak = env_peak * gr + (la+ra) * 0.5f * (1.0f - gr);
       }
        if ((count++ & 3) == 3) {
//          amp = rms_env_process(rms, sum * 0.25f);
         amp = rms_env_process(rms, (sum_l+sum_r) * 0.125f);
          sum = 0.0f;
        sum_l = 0.0f;
        sum_r = 0.0f;
  if (isnan(env_rms)) {
    // This can happen sometimes, but I don't know why
    env_rms = 0.0f;
  }

Then in default.pa Pulseaudio config file i chained 2 sc4_1882.so compressors one with Peak, 2nd with RMS.

load-module module-alsa-sink device=default sink_name=combined
load-module module-ladspa-sink sink_name=ladspa_output.sc42 label=sc4 plugin=sc4_1882 master=combined control=0,2,650,-30,2,6,7
load-module module-ladspa-sink sink_name=ladspa_output.sc4 label=sc4 plugin=sc4_1882 master=ladspa_output.sc42 control=1,180,350,-30,2,6,7
load-module module-ladspa-sink sink_name=ladspa_output.tap_equalizer label=tap_equalizer plugin=tap_eq master=ladspa_output.sc4 control=2,1,1,2,0,1,1,3,88,180,700,2100,5000,9000,13000,16000
..
set-default-sink ladspa_output.tap_equalizer

Somehow this setup creates a kind of 'depth' to stereo sounds/music.
I do not understand how/why songs seem to be having 'depth', i guess it has to do with calculating left and right channel gains independantly

Many thanks for the wonderful plugins you coded for LADSPA, and the modified code even sounds better than original sound of stereo music.

Thanks
S. W.

**Comment by sammerw** [comment]
Hello Steve
None of your email could be contacted, hence I created an 'issue', but its actually a 'feature'.
Thanks
S. W.

**Comment by swh** [comment]
Hi, calculating the left/right gains separately will do... things... to the stereo image :)

Probably not to everyone's taste - I'd encourage you to build your own plugin with a separate ID with your modifications, it's really easy.

I'm deliberately hard to contact BTW.

**Comment by sammerw** [comment]
Hi SteveDefinitely left/right considered in gains affects the heavily
'stereo' music, adding a 'depth' (since amplitude/gain is manifest in
near/far-ness of sound).Yep i'm ready to modify the sc4_1882, only
through the ladspa swh-plugins library, not an 'independant' plugin.The
modifications are minor enough so as to spinoff an sc5_XXXX 'stereo'
compressor with depth.
Its really mind blowing, when hearing classical orchestral music
!!Makes it as good (or better even) than 'surround sound' stuff.
ThanksSammer W.

**Comment by sammerw** [comment]
Hello SteveAttaching patchfile for sc4_1882 compressorThe change is not
noticeable to some people, while others notice the 'depth' of sound
immediately.I've listened from Bach, Debussy to Polyphia, Led Zep's
Bonzo's Montreux drumming, Telegraph Road of Dire Straits and just
about every classical, rock, alt-rock, heavy metal etc. stereo song
seems to have a *different* sound after twin chained compressors.
So it'd be good to spinoff a sc5_XXXX with the patch applied.You can
give it a listen by changing pulseaudio to have input to chained Peak
first, RMS second going to output.Its *different* but not completely as
to sound odd or bad, just that subtle 'depth' feel of sound comes
through.
ThanksSameer W.
On Tue, 2020-09-15 at 02:18 -0700, Steve Harris wrote:
> Hi, calculating the left/right gains separately will do... things...
> to the stereo image :)
> Probably not to everyone's taste - I'd encourage you to build your
> own plugin with a separate ID with your modifications, it's really
> easy.
> I'm deliberately hard to contact BTW.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--- ladspa-master/sc4_1882.xml	2020-07-30 15:46:02.000000000 +0530
+++ /home/sammer/ladspa-master/sc4_1882.xml	2020-09-16 06:38:45.608289292 +0530
@@ -25,6 +25,8 @@
 
       rms = rms_env_new();
       sum = 0.0f;
+      sum_l = 0.0f;
+      sum_r = 0.0f;
       amp = 0.0f;
       gain = 0.0f;
       gain_t = 0.0f;
@@ -64,6 +66,8 @@
 	const float ra = fabs(right_in[pos]);
 	const float lev_in = f_max(la, ra);
         sum += lev_in * lev_in;
+        sum_l += la * la;
+        sum_r =+ ra * ra;
 
         if (amp > env_rms) {
           env_rms = env_rms * ga + amp * (1.0f - ga);
@@ -74,12 +78,14 @@
         if (lev_in > env_peak) {
           env_peak = env_peak * ga + lev_in * (1.0f - ga);
         } else {
-          env_peak = env_peak * gr + lev_in * (1.0f - gr);
+          env_peak = env_peak * gr + (la+ra) * 0.5f * (1.0f - gr);
         }
 	round_to_zero(&env_peak);
         if ((count++ & 3) == 3) {
-          amp = rms_env_process(rms, sum * 0.25f);
+          amp = rms_env_process(rms, (sum_l+sum_r) * 0.125f);
           sum = 0.0f;
+          sum_l = 0.0f;
+          sum_r = 0.0f;
 	  if (isnan(env_rms)) {
 	    // This can happen sometimes, but I don't know why
 	    env_rms = 0.0f;
@@ -159,7 +165,7 @@
     <port label="amplitude" dir="output" type="control">
       <name>Amplitude (dB)</name>
       <p>The level of the input signal, in decibels.</p>
-      <range min="-40" max="+12"/>
+      <range min="-120" max="+22"/>
     </port>
 
     <port label="gain_red" dir="output" type="control">
@@ -188,6 +194,8 @@
     <instance-data label="as" type="float *" />
 
     <instance-data label="sum" type="float" />
+    <instance-data label="sum_l" type="float" />
+    <instance-data label="sum_r" type="float" />
     <instance-data label="amp" type="float" />
     <instance-data label="gain" type="float" />
     <instance-data label="gain_t" type="float" />
