### ISSUE TITLE
No built plugins available on website

### ISSUE THREAD

**Issue by LasOz** [swh/ladspa#72]
The download page on the website seems to have no built plugins available.

In fact, every page except the homepage is blank and has no information available on it.

![Capture](https://user-images.githubusercontent.com/9729621/126675317-35ef1fac-b30f-4719-9784-faaeb28df451.PNG)

Who owns and maintains the website for this project?

**Comment by swh** [comment]
Ah, thanks, the site is some ancient PHOP, I expect it broke when the ISP upgraded PHP, I’ll look into it.

- Steve

**Comment by swh** [comment]
Just fixed.
