### ISSUE TITLE
VyNil: make effect stop making noise when nothing is playing

### ISSUE THREAD

**Issue by JGHFunRun** [swh/ladspa#73]
This is really annoying and I wish it wouldn't make the vinyl crackle and white noise when there's nothing being played

**Comment by swh** [comment]
I can't tell if you're joking or not?

It's obviously meant to crackle even on silence.

If you need to mute it temporarily just move it to dry with a channel automation.

**Comment by JGHFunRun** [comment]
No I'm not, and the issue is not that it crackles when silence is playing, it's when _nothing_ is playing (ie I hit the play button it should start, pause it should stop, play start pause stop)

that's what I mean "nothing being played"

**Comment by JGHFunRun** [comment]
although everyone does seem to think I mean "detect if there's silence coming in, and if there is mute the noise"

**Comment by swh** [comment]
That's an issue for the host, the plugin doesn't know whether the host is currently playing anything, it just processes audio streams.

**Comment by JGHFunRun** [comment]
Ah ok I knew VSTs could get information about that stuff I would've thought LADSPA plugins can too
